# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-07-06 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170706_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='first_step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checklistname', to='backend.CheckListStep'),
        ),
    ]
